server:
  port: 8090
file:
  web-path: http://192.168.1.131:${server.port}${file.static}
  static: /static/pic
  image: /image
  audio: /audio
  video: /video
  pic: 
    path: D:/data/activity
  files:
    path: D:/data/activity
logging:
  config: classpath:logback/logback-spring.xml
  path: F:/logs 
spring:
  jmx:
    enabled: false 
  redis:
    database: 1
    host: 192.168.4.65
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 3000
  profiles:
    #开发模式
    active: dev
    #热部署生效
  devtools:
    restart:
      enabled: false
  jpa:
    properties:
       hibernate:
          show_sql: true

#jwt
jwt:
   secret: mySecret
   header: Authorization
   expiration: 604800
   tokenHead: Bearer
   
      
#自定义参数，可以迁移走
token:
  #token失效时间（不是refreshToken）(这是自定义的)(秒)
  expirationSeconds: 604800

  #默认7天登录有效(根据业务更改)
  validTime: 7
